#!/usr/bin/env python3
"""Package the one runtime registry; --check never writes generated assets."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
registry = root / "contracts/runtime-policy.json"
data = json.loads(registry.read_text())
assert data["prefix"] == "XGC2_XRPC_"
assert len({f["name"] for f in data["fields"]}) == len(data["fields"])
payload = json.dumps(data, indent=2, ensure_ascii=True) + "\n"
outputs = {
    "go/internal/policy/registry.json": payload,
    "python/xgc2_xrpc/_runtime_policy.json": payload,
    "rust/src/runtime_policy.json": payload,
    "node/runtime-policy.json": payload,
    "cpp/include/xgc2/xrpc/runtime_policy_registry.hpp":
        '// Generated by tools/generate-policy.py; edit contracts/runtime-policy.json.\n'
        '#pragma once\n#include <string_view>\nnamespace xgc2::xrpc {\n'
        'inline constexpr std::string_view runtime_policy_registry = R"XRPC(' + payload + ')XRPC";\n}\n',
}
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
stale = []
for name, content in outputs.items():
    path = root / name
    if args.check:
        if not path.is_file() or path.read_text() != content:
            stale.append(name)
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
if stale:
    parser.exit(1, "stale generated registries: " + ", ".join(stale) + "\n")
print("policy registry: " + ("checked" if args.check else "generated") + " 5 language assets")
