"""Resolve an explicit startup environment against the packaged common registry.

No environment is read by this module. The process composition root supplies
one snapshot and passes the resulting policy to its transport owners.
"""

import json
import re
import threading
from collections.abc import Mapping
from dataclasses import dataclass, replace
from functools import lru_cache
from importlib import resources
from types import MappingProxyType


class PolicyError(ValueError):
    """A rejected setting, without including its potentially sensitive value."""

    code = "invalid_argument"

    def __init__(self, field, reason):
        self.field = field
        super().__init__(f"{field}: {reason}")


class PolicyConflict(PolicyError):
    code = "conflict"


@dataclass(frozen=True)
class _Field:
    name: str
    type: str
    default: object
    dynamic: bool
    capability: str
    unit: str = ""
    values: tuple = ()
    maximum: int = 2147483647


@dataclass(frozen=True)
class _Registry:
    prefix: str
    fields: object
    capabilities: frozenset


_DECIMAL = re.compile(r"[1-9][0-9]*\Z", re.ASCII)


def _parse(field, raw):
    if field.type == "enum":
        if not isinstance(raw, str) or raw not in field.values:
            raise PolicyError(field.name, "exact declared enum token required")
        return raw
    # Deployment defaults and ceilings may use native integers. Booleans,
    # floats and arbitrary objects are never coerced to integer settings.
    if type(raw) is int:
        value = raw
    elif isinstance(raw, str):
        if len(raw) > 10 or _DECIMAL.fullmatch(raw) is None:
            raise PolicyError(field.name, "canonical positive ASCII decimal required")
        value = int(raw)
    else:
        raise PolicyError(field.name, "canonical positive ASCII decimal required")
    if value < 1 or value > field.maximum:
        raise PolicyError(field.name, "integer outside declared range")
    return value


@lru_cache(maxsize=1)
def _registry():
    # This distribution asset is generated by the common registry owner.
    data = json.loads(resources.files(__package__).joinpath("_runtime_policy.json").read_text(encoding="utf-8"))
    if (data.get("schema_version") != 1 or data.get("prefix") != "XGC2_XRPC_"
            or data.get("integer_syntax") != "[1-9][0-9]*"
            or data.get("integer_max") != 2147483647):
        raise RuntimeError("invalid generated XRPC runtime policy registry")
    fields = {}
    for raw in data["fields"]:
        if raw["name"] in fields or raw["type"] not in ("integer", "enum"):
            raise RuntimeError("invalid generated XRPC runtime policy field")
        field = _Field(
            name=raw["name"], type=raw["type"], default=raw["default"],
            dynamic=raw["dynamic"], capability=raw["capability"],
            unit=raw.get("unit", ""), values=tuple(raw.get("values", ())),
            maximum=min(raw.get("maximum", data["integer_max"]), data["integer_max"]),
        )
        _parse(field, field.default)
        fields[field.name] = field
    return _Registry(data["prefix"], MappingProxyType(fields),
                     frozenset(field.capability for field in fields.values()))


@dataclass(frozen=True)
class EffectiveField:
    value: object
    source: str
    dynamic: bool
    ceiling: object
    capability: str
    unit: str = ""
    source_detail: str = ""

    def snapshot(self):
        result = {"value": self.value, "source": self.source,
                  "dynamic": self.dynamic, "ceiling": self.ceiling,
                  "capability": self.capability}
        if self.unit:
            result["unit"] = self.unit
        if self.source_detail:
            result["source_detail"] = self.source_detail
        return result


class ResolvedPolicy:
    """Shared policy with atomic, revision-checked updates of declared live fields.

    Administrative authorization remains with the owner of the existing RPC
    interface. It must explicitly attest authorization when applying an update.
    Transport resource fields are immutable after startup; LOG_LEVEL is live.
    """

    def __init__(self, fields):
        self._fields = dict(fields)
        self._revision = 1
        self._lock = threading.Lock()

    @property
    def revision(self):
        with self._lock:
            return self._revision

    @property
    def fields(self):
        with self._lock:
            return MappingProxyType(dict(self._fields))

    def value(self, name):
        with self._lock:
            try:
                return self._fields[name].value
            except KeyError:
                raise PolicyError(name, "setting is not supported by this resolved policy") from None

    def snapshot(self):
        with self._lock:
            return {"revision": self._revision,
                    "fields": {name: field.snapshot() for name, field in self._fields.items()}}

    effective = snapshot

    def check_applied(self, *names):
        """Reject explicit settings that the selected process owners do not apply."""
        allowed = frozenset(names)
        with self._lock:
            for name, field in self._fields.items():
                if name not in allowed and field.source != "sdk_default":
                    raise PolicyError(name, "selected owners cannot enforce this setting")

    def mapped(self, mapping):
        """Map registry fields to constructor names, optionally converting units.

        A mapping value is an option name or an (option name, converter) pair.
        Unsupported fields are omitted; consumers validate required capabilities.
        """
        with self._lock:
            result = {}
            for name, option in mapping.items():
                if name not in self._fields:
                    continue
                value = self._fields[name].value
                if isinstance(option, tuple):
                    option, convert = option
                    value = convert(value)
                result[option] = value
            return result

    def update(self, changes, *, expected_revision, authorized=False):
        if authorized is not True:
            raise PermissionError("authenticated policy-update authorization required")
        if not isinstance(changes, Mapping):
            raise TypeError("policy updates must be a mapping")
        changes = dict(changes)
        registry = _registry()
        with self._lock:
            if type(expected_revision) is not int or expected_revision != self._revision:
                raise PolicyConflict("revision", "runtime policy revision conflict")
            updated = {}
            for name, raw in changes.items():
                if name not in self._fields:
                    raise PolicyError(name, "setting is not supported by this resolved policy")
                field = self._fields[name]
                if not field.dynamic:
                    raise PolicyError(name, "setting requires process restart")
                value = _parse(registry.fields[name], raw)
                if field.ceiling is not None and value > field.ceiling:
                    raise PolicyError(name, "resolved value exceeds declared ceiling")
                updated[name] = replace(field, value=value, source="administrative", source_detail="")
            if updated:
                self._fields.update(updated)
                self._revision += 1
            return {"revision": self._revision,
                    "fields": {name: field.snapshot() for name, field in self._fields.items()}}


def resolve_policy(environment, *, defaults=None, ceilings=None, capabilities=None,
                   deployment_source="deployment"):
    """Resolve one explicit snapshot; retain only declared effective policy.

    Capabilities select fields that the process can actually enforce. An
    explicitly supplied unsupported setting is rejected even if another input
    would override it. The whole registry is selected when capabilities is None.
    """
    if not isinstance(environment, Mapping):
        raise TypeError("explicit environment snapshot required")
    if defaults is not None and not isinstance(defaults, Mapping):
        raise TypeError("deployment defaults must be a mapping")
    if ceilings is not None and not isinstance(ceilings, Mapping):
        raise TypeError("product ceilings must be a mapping")
    if not isinstance(deployment_source, str):
        raise TypeError("deployment source must be a string")
    environment = dict(environment)
    defaults, ceilings = dict(defaults or {}), dict(ceilings or {})
    registry = _registry()
    if isinstance(capabilities, str):
        raise TypeError("capabilities must be a collection of declared names")
    enabled = registry.capabilities if capabilities is None else frozenset(capabilities)
    for capability in enabled:
        if capability not in registry.capabilities:
            raise PolicyError(capability, "unknown runtime policy capability")
    effective = {
        name: EffectiveField(field.default, "sdk_default", field.dynamic, None,
                             field.capability, field.unit)
        for name, field in registry.fields.items() if field.capability in enabled
    }

    def selected(name, *, environment_name=None):
        field = registry.fields.get(name)
        if field is None:
            raise PolicyError(environment_name or name, "unknown runtime setting")
        if field.capability not in enabled:
            raise PolicyError(name, "setting is not enforced by selected capabilities")
        return field

    def apply(name, raw, source, *, environment_name=None):
        field = selected(name, environment_name=environment_name)
        if source == "environment" and not isinstance(raw, str):
            raise PolicyError(name, "environment setting must be a string")
        value = _parse(field, raw)
        effective[name] = replace(effective[name], value=value, source=source,
                                  source_detail=deployment_source if source == "deployment" else "")

    for name, raw in defaults.items():
        apply(name, raw, "deployment")
    for name, raw in environment.items():
        if isinstance(name, str) and name.startswith(registry.prefix):
            apply(name[len(registry.prefix):], raw, "environment", environment_name=name)
    for name, raw in ceilings.items():
        field = selected(name)
        if field.type != "integer":
            raise PolicyError(name, "ceiling requires a supported integer field")
        ceiling = _parse(field, raw)
        if effective[name].value > ceiling:
            raise PolicyError(name, "resolved value exceeds declared ceiling")
        effective[name] = replace(effective[name], ceiling=ceiling)
    return ResolvedPolicy(effective)
